#!/bin/sh

STUDY_MINUTES=25
BREAK_MINUTES=5

print_break() {
    figlet -c break -w $(tput cols)
}

print_study() {
    figlet -c study -w $(tput cols)
}

print_help() {
    echo "--- Help ---"
    echo "-h -- print this menu"
    echo "-s -- amount of study in minutes between breaks"
    echo "-b -- amount of break in minutes between studies"
}

countdown_study() {
    clear
    print_study
    seconds=$(($STUDY_MINUTES*60)); date1=$((`date +%s` + $seconds)); 
    while [ "$date1" -ge `date +%s` ]; do 
        echo -ne "$(date -u --date @$(($date1 - `date +%s` )) +%H:%M:%S)\r"; 
    done
}

countdown_break() {
    clear
    print_break
    seconds=$(($BREAK_MINUTES*60)); date1=$((`date +%s` + $seconds));
    while [ "$date1" -ge `date +%s` ]; do 
        echo -ne "$(date -u --date @$(($date1 - `date +%s` )) +%H:%M:%S)\r"; 
    done
}

while getopts "hs:b:" opt; do
    case "$opt" in
        h)
            print_help
            exit 0
            ;;
        s)
            STUDY_MINUTES=$OPTARG
            ;;
        b)
            BREAK_MINUTES=$OPTARG
            ;;
    esac
done

while true; do
    countdown_study
    beep
    countdown_break
    beep
done
